### ISSUE TITLE
Is it possible to add Application Identifier 310-369 as FixedLengthGS1Field<double?>

### ISSUE THREAD

**Issue by pejoh-eg** [DacoTaco/BarcodeParserBuilder#10]
I like your parser for GS1 barcodes but I run into trouble with one barcode with prefix 311 (Length in m). When I looked in the source code I notified that today only Application Identifier (AI) 310 (Weight in KG) and 320(Weight in Lb) are included dimensions.
There are a lot of more prefix (310-369) that describe dimensions and have exactly same logic as these two field (310/320).
All these prefix describe the items dimensions like size, weight, area in different units.

Would it be possible to change GS1Barcode.cs to handle this?
I attach a proposal for new version of GS1Barcode
[GS1Barcode.txt](https://github.com/DacoTaco/BarcodeParserBuilder/files/13202321/GS1Barcode.txt)

I added those prefix as FixedLength and remove duplicates prefix
It would be nice if this is possible. I'd rather it be include in your version than make my own local version for handling this.

**Comment by DacoTaco** [comment]
nice, you reported this while i am off work haha.

lets see, parsing doubles is already in the GS1 barcode, which would be the biggest part so thats good.

so from what i gather, you just want to expose the Application Identifiers as GS1Barcode properties?

**Comment by pejoh-eg** [comment]
Exactly. For example AI 311 is now stored as a separate field but as a "String". The logic for handle this as a double with first number as a decimal place is now handle by me in the code. It would be nice to have this logic in the nugets just like prefix 310 so I can get the "Value" in double direct.

**Comment by DacoTaco** [comment]
didn't notice the PR, ill take a look at it and compare it with the specs to make sure there are no mistakes!

**Comment by pejoh-eg** [comment]
Here are the spec. I looked into.
https://ref.gs1.org/standards/genspecs/

**Comment by DacoTaco** [comment]
PR merged. want me to make a preview version for nuget or is this a change you aren't waiting for?

**Comment by pejoh-eg** [comment]
If it's possible to make a nuget packages with this changes I will be happy. I working with this problem right now.

**Comment by DacoTaco** [comment]
i have pushed a 0.1.3-preview1 to validate the changes with. 
it seems to have been validated and listed on nuget ! :)

**Comment by pejoh-eg** [comment]
Thanks, have a good day. If I found more I'm pleased to help you out.

**Comment by DacoTaco** [comment]
no problem! changes like this can benefit everyone !
