### ISSUE TITLE
Having trouble adding application identifier for GLN (414).

### ISSUE THREAD

**Issue by marydeshon** [DacoTaco/BarcodeParserBuilder#17]
This is a great package!
I  added the GLN AI which is 414 fixed length of 13 to the field collection.
In testing it fails to parse and seems to be that the AI is being parsed as 41 instead of 414.
Is there something "special" I need to do for 3 char identifier on a fixed length field?
I see all of the float versions so maybe something like that is needed?
I am using ]d2 for  tesing.

**Comment by DacoTaco** [comment]
hm, this probably has to do with the [code currently kinda cheating and parsing all AI's starting with 41 as a random part](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder/Barcodes/GS1/GS1Barcode.cs#L96) 

i think all 41x fields will need to be added properly and have its data type & length set [just like what we did with 31x](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder/Barcodes/GS1/GS1Barcode.cs#L24-L30) which were thankfully all double types 

thankfully, a quick look at the list @ https://ref.gs1.org/ai/ seems to show all 41x AI's are string integers, so i think just having them defined as string will do.

to be correct though, we'd need to somehow read it in as a string that can only have digits, but that would need more work.
as a first step, i think defining the AI's would get it going for now :)

will you be making a PR to implement these?

**Comment by DacoTaco** [comment]
ye, 25x is the same. [we read everything starting with 25 into the one field](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder/Barcodes/GS1/GS1Barcode.cs#L86) hehe

**Comment by marydeshon** [comment]
Hi I just created a pull request. Could you please review at your convenience. Thank you!!

**Comment by DacoTaco** [comment]
@marydeshon : PR is merged, thanks a lot!
do you want me to create a new preview package to upload to nuget so you can use it?

**Comment by marydeshon** [comment]
Yes, please!

**Comment by DacoTaco** [comment]
aight, a new tag has been created and pushed to nuget.org. `0.1.4-preview2` should be available in the next half hour :)
thanks for your contribution !
