### ISSUE TITLE
MSI Barcode not recognized

### ISSUE THREAD

**Issue by gachu1686** [DacoTaco/BarcodeParserBuilder#5]
HI, I am using your latest version of Barcode Parser, and I have a barcode that is not getting parsed.
I believe it is a MSI barcode and I expect that to be parsed,
Here is my raw barcode string:
4945227401

Can you please take a look at this, and provide me an update of why this is not working, I have multiple of these kind of barcodes that we are not able to parse.
Thanks

**Comment by DacoTaco** [comment]
the current code detects "4945227401" to have an invalid check digit. it expects a 5 at the end, not 1.

can you verify the barcode and/or show me the original barcode for me to investigate?

**Comment by DacoTaco** [comment]
btw, if you have issues with barcodes not parsing, you can always use the specific barcode unit tests to try them out
they can be found here : https://github.com/DacoTaco/BarcodeParserBuilder/tree/main/BarcodeParserBuilder.UnitTests/Barcodes

for example, the MSI unit tests are found [here](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder.UnitTests/Barcodes/MSI/MsiBarcodeParserBuilderTestFixture.cs#L40-L98)

**Comment by gachu1686** [comment]
Thanks for the information, 
Am adding a reference where you can find the original barcode. The parser currently returns this message - "Failed to parse barcode : no parser could accept barcode."
I thought it was a MSI barcode, but i might be wrong. Can you please investigate and let me know if the parser could handle this barcode.
![barcode (9)](https://user-images.githubusercontent.com/56278584/210458968-1ffac5f6-726e-4d7a-8f12-b69c16dfff3f.gif)

**Comment by DacoTaco** [comment]
it looks to be something (msi?) in a CODE128 formatted barcode.
however, i have a feeling there is no checkdigit in this one somehow, or its check digit is wrong?

do you have barcodes that do work, and can you check with the party that generates these barcodes if they have a check digit and what it is? maybe they can validate the barcode & its code?

MSI also has a schema of 'no checkdigit', but due to those barcode not having any way to verify they are an MSI or not, i don't support those at the moment.

**Comment by gachu1686** [comment]
I did verify with the other barcodes and it looks like this one does not have the check digit.
Thanks for the quick turn around and the investigation.

**Comment by DacoTaco** [comment]
no problem. is the issue resolved now or is there anything i need to change?

**Comment by gachu1686** [comment]
There is nothing to be changed. The issue
