### ISSUE TITLE
Use symbology prefixes for all barcodes

### ISSUE THREAD

**Issue by neemevool** [DacoTaco/BarcodeParserBuilder#6]
I see that for GS1-128 the symbology prefix ]C1 is used to recognize the barcode. Same is not used for other types. Could it be possible to use prefixes which scanner provides, for all barcodes? Currently it is kind of inconsistent

**Comment by DacoTaco** [comment]
hi, thanks for this report!

it is indeed better to have all barcode parsers be able to handle their prefixes, but i do not know the prefixes besides the GS1/EAN prefix.

can you provide the value's for the other barcodes and an example (to use in the unit tests)

**Comment by neemevool** [comment]
Different scanners are able to use different prefixes, some of them are legacy like Sunmi ID etc. I think most reasonable is to use so-called AIM ID-s, formerly defined by AIM, now ISO/IEC standard. Article on the Zebra homepage: https://supportcommunity.zebra.com/s/article/What-is-AIM-identifier-for-Barcode?language=en_US

One good overwiew: https://www.gs1.org/sites/default/files/eu2018-574requireddatacapturespecifications.pdf

Some background is on the: https://barcodeguide.seagullscientific.com/content/AIM.htm
More background: https://www.aimglobal.org/

**Comment by DacoTaco** [comment]
hm, this is interesting to say the least. i knew the `]C1` was part of the GS1-128/EAN-128 specs, hence it is implemented but i didn't know about the rest.

im reading mixed things here though. the `]C1` *must* be in a EAN-128 at the start of a barcode, as its specs define, but the zebra docs mention the prefix to be added by the scanner (making me believe it is a setting of the scanner?)
however, the GS1 specs mention other prefixes that i have never seen in the wild before... :/

**Comment by neemevool** [comment]
Thats why Im saying it should be optional. But usage of the scanner-provided barcode ID would be helpful. Scanner producers make thereby detection of the barcode much easier. For example here are options from Sunmi scanner settings. All well-known brands support AIM ID-s. 
![image](https://user-images.githubusercontent.com/39978067/229276379-157334f5-8c15-486e-989a-5f5e63b48e71.png)

**Comment by DacoTaco** [comment]
just throwing documentation out here, i am basing my aim identifiers on a more complete list found on honeywell's website : https://support.honeywellaidc.com/s/article/List-of-barcode-symbology-AIM-Identifiers

@neemevool, do you happen to have more test barcodes i could use in my unit tests besides the `]E01234567890128`?

**Comment by neemevool** [comment]
There are few, which I retyped from my scanner. 
]d20108430215011539112212221724022021S3736
]d2000761332612057038641725063010E1999E2<GS>3050<GS>24010208034
]d201040156309281941022200273<GS>112208011724073124005694302001
]C1011234567890123115991231
the <GS> represents character 0x1D, which I have to encode with my scanner, otherwise it cant be transmitted as keystrokes
So before I feed it to your library I replace it:
_rawbarcode = _rawbarcode.Replace("<GS>", $"{(char)0x1D}");

More barcodes can be generated at 
https://www.bcgen.com/linear-barcode-creator.html
But I think you dont have actual scanner handy? If you want to test some exotic or more prefixes, you can point me images, I can read them with the scanner and send it.

**Comment by DacoTaco** [comment]
ye, i don't have a scanner nor barcodes handy haha.

i'll take your examples as test strings for my unit tests, thanks!

**Comment by DacoTaco** [comment]
@neemevool : i have uploaded a preview version on nuget. can you verify it works as expected?

**Comment by DacoTaco** [comment]
@neemevool : any updates on your end?

**Comment by neemevool** [comment]
Sorry, did not have time so far. I will download it and test at my end coming week.

**Comment by neemevool** [comment]
Hello! Downloaded and built small sample console app. Looks good. I peeked into the changeset and how it is implemented. If Im correct, then when AIM prefix is given, then it does not try to guess other types except the one in the prefix. However, reflection in .NET 6 seems to be so good that differences between barcode with prefix (no guessing) and without prefix (guessing) are almost same (I did just loop of 1000). So in reality not much differences in speed. But what matters is possibility to validate the barcode with the prefix. Meaning, if the barcode claims to be GS1 by the prefix ]Q3 then when it is invalid, it should not be tried to be parsed as something else. For example, ]Q31234567890128 should _not_ be tried as EAN13. And thats working. So looks good. 
Just one thing for future. I dont know if it may be the case at all. But I would add possibility for the explicit option in the constructor for example to say that I will feed the parser with AIM prefixes. Or in future with some other prefixes too? 
But thats not critical anymore. For me it is working fine. Really good job, thank you!

**Comment by DacoTaco** [comment]
alright! 
ill close this issue if it is correct right now.
despite it maybe not being that much faster in theory, in practice it can be faster and it is more correct to cut off any barcode prefix if you can. for example a ]d3 is something a MSI barcode shouldn't bother with unless its specifically part of its barcode. 

Thanks for reporting this! :)
