### ISSUE TITLE
GS1 DataMatrix support?

### ISSUE THREAD

**Issue by agnespoodle** [DacoTaco/BarcodeParserBuilder#9]
This is slick, but not supporting GS1 DataMatrix (2D barcodes, pharma industry standard). I've started looking into modifying what you've got here, but if you're willing to incorporate it, you're no doubt faster than I am.

**Comment by DacoTaco** [comment]
wdym not supporting GS1 datamatrix?
do you have an example that isn't working?

2D GS1 barcodes should work, specifically health care related ones :/

**Comment by agnespoodle** [comment]
I tried a couple 2D scans off some old (expired in 2021) drug boxes and it said invalid, and looking at the code I didn't see support for 414 GLN and 254 GLN Extension so I probably posted in a caffeinated haste.  GS1 scans worked great.  But it installed and worked well via Nuget, so kudos to you!

**Comment by DacoTaco** [comment]
you are correct that it is missing the 414 & 254 application identifiers.
it has [a rudimentary support](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder/Barcodes/GS1/GS1Barcode.cs#L65) but it just loads all data until it finds a <gs>. if it doesn't contain one, it loads everything into it hehe

i tried parsing 0100304720400301211006155205193317210228101012131 using [one of the many unit tests](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs#L211) and i saw it parsed the Product code. it detected the product code as 00304720400301, or a National drug code 0472040030.
after that its trying to put 1006155205193317210228101012131 in application identifier 21. 
it fails there are [segment 21 is set to have a max length of 20 characters (..21)](https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder/Barcodes/GS1/GS1Barcode.cs#L29)

this is [following the GS1 specs](https://ref.gs1.org/standards/genspecs/#%5B%7B%22num%22%3A484%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C50%2C732%2C0%5D) so seems like that barcode is invalid? is the copy paste missing a group separator somewhere?

the same thing happens with that second barcode too

**Comment by agnespoodle** [comment]
It may be these 2D codes are too outdated or otherwise just weird.  0100304720400301211006155205193317210228101012131 should break down into:
01 (GTIN)
00304720400301
21 (Serial Number)
10061552051933
17 (Exp Date)
210228
10 (Lot Number)
1012131

Based on the box and the human-readable format.  But again, it's old, so maybe I'm working with crap codes.  I'm not reading any group separators.  Those codes I posted in the edit were direct scans.

**Comment by DacoTaco** [comment]
hm, a serial number should end with a group separator unless it is exactly 20 characters.
maybe the scanner is dropping it ?
can you post an image of the barcodes themselves?

**Comment by agnespoodle** [comment]
![clobetasol](https://github.com/DacoTaco/BarcodeParserBuilder/assets/55540274/f4dad4d7-560c-4d97-8159-f7ba968f8b8f)

**Comment by DacoTaco** [comment]
yup, your scanner seems to be discarding the group separators.
my phone , using the [scanbot sdk](https://play.google.com/store/apps/details?id=io.scanbot.demo.barcodescanner&hl=nl&gl=US), read out `gs`01003047204003012110061552051933`gs`17210228101012131 which does parse correctly

can you check your scanner's settings?

**Comment by agnespoodle** [comment]
Sigh.  Thanks.  If I use the QR app on my phone, I see the separators.  I'm using a TEEMI handheld scanner, so I'll try and see if there's a setting I can change.  Thanks for the help, man.  Turns out your code is fine and my scanner is the problem.

**Comment by DacoTaco** [comment]
haha, no problem.
im going to close this issue, but if you ever come across an issue don't hesitate to report it!

this project exists to help everyone that uses it and it can only do so by getting issues reported or pull requests made to improve it
